### ISSUE TITLE
403 Error

### ISSUE THREAD

**Issue by VictorKabata** [google-checks/checks-app-scan-github-action#3]
The workflow fails with error:
```
Error: failed to generate report API: googleapi: Error 403: The caller does not have permission, forbidden
```

**Comment by evanadwyer-pronoid-software** [comment]
I'm experiencing the same, with no further information provided... Followed all the steps outlined [here](https://developers.google.com/checks/guide/integrate/ci-cd/ci-cd-setup?plugin=github-actions). Can't even get it to run with just my user account via the CLI... Unsure on what permission may be missing

**Comment by evanotero** [comment]
Thanks for flagging this issue Victor and Evan. We're investigating the issue now and will provide you an update soon if it's a bug or if there's missing configuration instructions.

**Comment by evanotero** [comment]
**Update**: We've identified the issue. We're blocking _Essentials_ tier Checks accounts from calling the API, which is a bug. We'll be submitting a fix to enable the API for the _Essentials_ tier and rolling out a new version of the API. I'll send an update here as soon as that change is live.

Appreciate your patience!

**Comment by evanotero** [comment]
The fix is now live in production and you should no longer get a `403` error. Let me know if you run into any further issues and thank you for using our CI/CD functionality!

**Comment by evanadwyer-pronoid-software** [comment]
Works for me now, thanks for the quick fix!

**Comment by evanadwyer-pronoid-software** [comment]
I've checked it with the CI workflow I was trying and looks like it works
now! Thanks for the quick fix on this one!
